name: PlayerCount
main: no.nkopperudmoen.PlayerCount
version: 1.0-SNAPSHOT
api-version: 1.19
author: itsNikolai11
commands:
  spiller:
    description: Sjekker info om en spiller.
    usage: /spiller (spiller)
    aliases:
      - seen
  ontime:
    description: Sjekker din ontime
    usage: /ontime
    aliases:
      - tid
      - time